"""add minutes_to_complete to recipes

Revision ID: 4d8ea0c38a23
Revises: bcf0cbdc17c3
Create Date: 2025-09-24 18:01:47.710676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8ea0c38a23'
down_revision = 'bcf0cbdc17c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('minutes_to_complete', sa.Integer(), nullable=False))
        batch_op.alter_column('instructions',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_recipes_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_recipes_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.alter_column('instructions',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('minutes_to_complete')

    # ### end Alembic commands ###
